### ISSUE TITLE
tests fails on windows

### ISSUE THREAD

**Issue by aleksandervines** [nansencenter/nansat#202]
It seems that the reason could be related to files not being closed. I also notice that on default, gui windows are opened up during the tests, could be related.

ERROR: test_export2thredds_arctic_long_lat (nansat.tests.test_nansat.NansatTest)
Traceback (most recent call last):
  File "C:\Users\alevin\AppData\Local\Continuum\miniconda2\conda-bld\nansat_1515768613653\_test_env\lib\site-packages\nansat\tests\test_nansat.py", line 378, in test_export2thredds_arctic_long_lat
    time=datetime.datetime(2016, 1, 20))
  File "C:\Users\alevin\AppData\Local\Continuum\miniconda2\conda-bld\nansat_1515768613653\_test_env\lib\site-packages\nansat\nansat.py", line 877, in export2thredds
    os.remove(tmpName)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\alevin\\appdata\\local\\temp\\tmppojfix.nc'

ERROR: test_export2thredds_longlat_dict (nansat.tests.test_nansat.NansatTest)
Traceback (most recent call last):
  File "C:\Users\alevin\AppData\Local\Continuum\miniconda2\conda-bld\nansat_1515768613653\_test_env\lib\site-packages\nansat\tests\test_nansat.py", line 440, in test_export2thredds_longlat_dict
    n.export2thredds(tmpfilename, {'L_469': {'type': '>i1'}})
  File "C:\Users\alevin\AppData\Local\Continuum\miniconda2\conda-bld\nansat_1515768613653\_test_env\lib\site-packages\nansat\nansat.py", line 877, in export2thredds
    os.remove(tmpName)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\alevin\\appdata\\local\\temp\\tmpj7gvgc.nc'

ERROR: test_export2thredds_longlat_list (nansat.tests.test_nansat.NansatTest)
Traceback (most recent call last):
  File "C:\Users\alevin\AppData\Local\Continuum\miniconda2\conda-bld\nansat_1515768613653\_test_env\lib\site-packages\nansat\tests\test_nansat.py", line 425, in test_export2thredds_longlat_list
    n.export2thredds(tmpfilename, ['L_469'])
  File "C:\Users\alevin\AppData\Local\Continuum\miniconda2\conda-bld\nansat_1515768613653\_test_env\lib\site-packages\nansat\nansat.py", line 877, in export2thredds
    os.remove(tmpName)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\alevin\\appdata\\local\\temp\\tmpq_9fwf.nc'

ERROR: Test export and following import of data with bands containing
Traceback (most recent call last):
  File "C:\Users\alevin\AppData\Local\Continuum\miniconda2\conda-bld\nansat_1515768613653\_test_env\lib\site-packages\nansat\tests\test_nansat.py", line 143, in test_export_netcdf
    os.unlink(self.tmpfilename)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\alevin\\AppData\\Local\\Continuum\\miniconda2\\conda-bld\\nansat_1515768613653\\_test_env\\lib\\site-packages\\nansat\\tests\\data\\test_data\\test.nc'

ERROR: Test export of the arctic data without GCPS
Traceback (most recent call last):
  File "C:\Users\alevin\AppData\Local\Continuum\miniconda2\conda-bld\nansat_1515768613653\_test_env\lib\site-packages\nansat\tests\test_nansat.py", line 946, in test_export_netcdf_arctic
    os.unlink(self.tmpfilename)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\alevin\\AppData\\Local\\Continuum\\miniconda2\\conda-bld\\nansat_1515768613653\\_test_env\\lib\\site-packages\\nansat\\tests\\data\\test_data\\test.nc'

ERROR: Test export of complex data with pixelfunctions
Traceback (most recent call last):
  File "C:\Users\alevin\AppData\Local\Continuum\miniconda2\conda-bld\nansat_1515768613653\_test_env\lib\site-packages\nansat\tests\test_nansat.py", line 933, in test_export_netcdf_complex_remove_meta
    os.unlink(self.tmpfilename)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\alevin\\AppData\\Local\\Continuum\\miniconda2\\conda-bld\\nansat_1515768613653\\_test_env\\lib\\site-packages\\nansat\\tests\\data\\test_data\\test.nc'

----------------------------------------------------------------------
Ran 138 tests in 10.124s

FAILED (errors=6)

**Comment by aleksandervines** [comment]
solved half of these by moving os.unlink(self.tmpfilename) to teardown. Still an issue within export2thredds though
