### ISSUE TITLE
test_difitize_points requires DISPLAY

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nansat#283]
#### Problem
The test requires display, but the method can also work in non-interactive method.
The test should be skipped if DISPLAY is not available. It is skipped on Travis.
But builds for conda-forge fail, because this test is not skipped for some reason (some DISPLAY variable is apparently available)
#### Solution
 * Remove plt.ion()
 * Do npt skip if DISPLAY is not available

**Comment by akorosov** [comment]
The tests test_onclick_multilines  and  test_onclick in nansat.tests.test_pointbrowser.PointBrowserTest still fail when Nansat is build for conda-forge on CircleCI:
```
======================================================================
ERROR: test_onclick (nansat.tests.test_pointbrowser.PointBrowserTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/feedstock_root/build_artefacts/nansat_1520636878442/_t_env/lib/python2.7/site-packages/nansat/tests/test_pointbrowser.py", line 36, in setUp
    self.point = PointBrowser(data)
  File "/feedstock_root/build_artefacts/nansat_1520636878442/_t_env/lib/python2.7/site-packages/nansat/pointbrowser.py", line 75, in __init__
    self.fig = plt.figure()
  File "/feedstock_root/build_artefacts/nansat_1520636878442/_t_env/lib/python2.7/site-packages/matplotlib/pyplot.py", line 548, in figure
    **kwargs)
  File "/feedstock_root/build_artefacts/nansat_1520636878442/_t_env/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/feedstock_root/build_artefacts/nansat_1520636878442/_t_env/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 167, in new_figure_manager_given_figure
    canvas = cls.FigureCanvas(figure)
  File "/feedstock_root/build_artefacts/nansat_1520636878442/_t_env/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 24, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "/feedstock_root/build_artefacts/nansat_1520636878442/_t_env/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 234, in __init__
    _create_qApp()
  File "/feedstock_root/build_artefacts/nansat_1520636878442/_t_env/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 125, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
-------------------- >> begin captured logging << --------------------
matplotlib.backends: DEBUG: backend Qt5Agg version 5.6
--------------------- >> end captured logging << ---------------------
```
