### ISSUE TITLE
TestExporter exports into the same test.nc file

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nansat#292]
#### Problem
TestExporter exports into the same test.nc file. That causes problems when testing on windows with appveyor. 
#### Solution
Export into a new file in each test.
#### Tasks
Generate test filename for each test.

**Comment by akorosov** [comment]
Apparently a file is not closed somewhere inside _post_proc_thredds:
```
1197======================================================================
1198ERROR: test_export2thredds_arctic_long_lat (nansat.tests.test_exporter.ExporterTest)
1199----------------------------------------------------------------------
1200Traceback (most recent call last):
1201  File "C:\bld\nansat_1521018443046\_t_env\lib\site-packages\nansat\tests\test_exporter.py", line 262, in test_export2thredds_arctic_long_lat
1202    n.export2thredds(tmpfilename, bands, time=datetime.datetime(2016, 1, 20))
1203  File "C:\bld\nansat_1521018443046\_t_env\lib\site-packages\nansat\exporter.py", line 280, in export2thredds
1204    self._post_proc_thredds(tmp_filename, filename, bands, dstBands, time, global_metadata)
1205  File "C:\bld\nansat_1521018443046\_t_env\lib\site-packages\nansat\exporter.py", line 413, in _post_proc_thredds
1206    os.remove(tmp_filename)
1207WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\tmpc4ylwq.nc'
```

**Comment by akorosov** [comment]
The error also appear in tearDown but only for one test:
```
1233======================================================================
1234ERROR: Test export of the arctic data without GCPS
1235----------------------------------------------------------------------
1236Traceback (most recent call last):
1237  File "C:\bld\nansat_1521018443046\_t_env\lib\site-packages\nansat\tests\test_exporter.py", line 67, in tearDown
1238    os.unlink(self.tmpfilename)
1239WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:\\bld\\nansat_1521018443046\\_t_env\\lib\\site-packages\\nansat\\tests\\data\\test_data\\tmpvbguja.nc'
1240
1241======================================================================
1242ERROR: Test export of the arctic data without GCPS
1243----------------------------------------------------------------------
1244Traceback (most recent call last):
1245  File "C:\bld\nansat_1521018443046\_t_env\lib\site-packages\nansat\tests\test_exporter.py", line 67, in tearDown
1246    os.unlink(self.tmpfilename)
1247WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:\\bld\\nansat_1521018443046\\_t_env\\lib\\site-packages\\nansat\\tests\\data\\test_data\\tmptpcbfl.nc'
1248
1249--------------------------------------------
```
