### ISSUE TITLE
ExporterTest.test_export_netcdf and similar fail in Virtual Machine

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nansat#315]
Several tests where a temporary netcdf file is created fail when run in a virtual machine:
```
======================================================================
ERROR: Test export and following import of data with bands containing np.nan values
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/nansat/tests/test_exporter.py", line 91, in test_export_netcdf
    n.export(self.tmp_filename)
  File "/vagrant/nansat/exporter.py", line 151, in export
    dataset = gdal.GetDriverByName(driver).CreateCopy(filename, export_vrt.dataset, options=options)
  File "/home/vagrant/Miniconda3-4.3.31-Linux-x86_64/envs/py3nansat/lib/python3.6/site-packages/osgeo/gdal.py", line 1546, in CreateCopy
    return _gdal.Driver_CreateCopy(self, *args, **kwargs)
RuntimeError: /vagrant/nansat/tests/data/test_data/tmpa12zaxs2.nc: No such file or directory

----------------------------------------------------------------------
Ran 1 test in 0.166s

FAILED (errors=1)
```
These tests fail:
test_time_coverage_metadata_of_exported_equals_original
test_special_characters_in_exported_metadata
test_geolocation_of_exportedNC_vs_original
test_export_netcdf_complex_remove_meta
test_export_netcdf

**Comment by jonbergh** [comment]
This seems to be related to issue #331 , the changes made in `nansat_test_base.py` should solve this.

**Comment by mortenwh** [comment]
Do all the tests pass now? Then I guess @akorosov can close this issue....
