### ISSUE TITLE
Install nansat

### ISSUE THREAD

**Issue by geom16011** [nansencenter/nansat#456]
Tried to install nansat using pip install nansat and i get the following error:

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-build-8xledz81\nansat\setup.py", line 76, in <module>
        path = os.environ['LIB'].split(';')
      File "c:\users\user\appdata\local\programs\python\python36\lib\os.py", line 669, in __getitem__
        raise KeyError(key) from None
    KeyError: 'LIB'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-build-8xledz81\nansat\

Any ideas?

**Comment by akorosov** [comment]
Hard to say. Maybe MS VisualStudio is not installed? We cannot provide
support for Windows at the moment, sorry!
Please consider using Docker.

пт, 24 янв. 2020 г. в 14:11, geom16011 <notifications@github.com>:
