### ISSUE TITLE
Support for Cartopy 0.20

### ISSUE THREAD

**Issue by aperrin66** [nansencenter/nansat#512]
Using nansat with Cartopy 0.20, scipy 1.7, gdal 3.4, matplotlib 3.5 and numpy 1.21 does not work.
Several tests fail:

**nansat.tests.test_exporter.TestExporter__export2thredds.test_example1**, **test_example2** and **test_example3**:
```
Traceback (most recent call last):
  File "/workspace/nansat/tests/test_exporter.py", line 404, in test_example1
    n.export2thredds(self.filename_exported, mask_name='mask', no_mask_value=1)
  File "/workspace/nansat/exporter.py", line 259, in export2thredds
    global_metadata = Exporter._set_global_metadata(created, data, metadata)
  File "/workspace/nansat/exporter.py", line 426, in _set_global_metadata
    min_lon, max_lon, min_lat, max_lat = data.get_min_max_lon_lat()
  File "/workspace/nansat/domain.py", line 693, in get_min_max_lon_lat
    lon_grd, lat_grd = self.get_geolocation_grids()
  File "/workspace/nansat/domain.py", line 408, in get_geolocation_grids
    dst_srs=dst_srs)
  File "/workspace/nansat/domain.py", line 828, in transform_points
    return self.vrt.transform_points(colVector, rowVector, dst2src=DstToSrc, dst_srs=dst_srs)
  File "/workspace/nansat/vrt.py", line 1432, in transform_points
    transformer = gdal.Transformer(self.dataset, dst_ds, options)
  File "/venv/lib/python3.7/site-packages/osgeo/gdal.py", line 4472, in Transformer
    return _gdal.Transformer(*args)
RuntimeError: The transformation is already "north up" or a transformation between pixel/line and georeferenced coordinates cannot be computed for /vsimem/7W8EZ0RNSW.vrt. There is no affine transformation and no GCPs. Specify transformation option SRC_METHOD=NO_GEOTRANSFORM to bypass this check.
```

**nansat.tests.test_tools.ToolsTest.test_save_domain_map**:
```
Traceback (most recent call last):
  File "/workspace/nansat/tests/test_tools.py", line 98, in test_save_domain_map
    self.assertEqual(i.info['dpi'], (100, 100))
AssertionError: Tuples differ: (99.9998, 99.9998) != (100, 100)

First differing element 0:
99.9998
100

- (99.9998, 99.9998)
+ (100, 100)
```

**nansat.tests.test_nansat.NansatTest.test_resize_complex_alg_average**:
```
Traceback (most recent call last):
  File "/workspace/nansat/tests/test_nansat.py", line 223, in test_resize_complex_alg_average
    self.assertEqual(len(w), 1)
AssertionError: 2 != 1
```

**Comment by aperrin66** [comment]
The error in **nansat.tests.test_nansat.NansatTest.test_resize_complex_alg_average** is due to this warning which was added in numpy:
```
`np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.\nDeprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
