### ISSUE TITLE
a error of the ASAR  *N1 format data

### ISSUE THREAD

**Issue by GaotTian** [nansencenter/nansat#551]
Traceback (most recent call last):
  File "D:\Python_code\sea_ice_drift-master\cartopy_show_ASAR.py", line 17, in <module>
    n = Nansat(filename,mapper='ASAR')
  File "C:\software\anoconda3\envs\nansat3.9\lib\site-packages\nansat\nansat.py", line 156, in __init__
    self.vrt = self._get_mapper(mapper, **kwargs)
  File "C:\software\anoconda3\envs\nansat3.9\lib\site-packages\nansat\nansat.py", line 1135, in _get_mapper
    tmp_vrt = nansatMappers[mappername](self.filename, gdal_dataset, metadata, **kwargs)
  File "C:\software\anoconda3\envs\nansat3.9\lib\site-packages\nansat\mappers\mapper_asar.py", line 49, in __init__
    self.setup_ads_parameters(filename, gdalMetadata)
  File "C:\software\anoconda3\envs\nansat3.9\lib\site-packages\nansat\mappers\envisat.py", line 212, in setup_ads_parameters
    raise WrongMapperError
nansat.exceptions.WrongMapperError
Exception ignored in: <function VRT.__del__ at 0x000002E7D795B700>
Traceback (most recent call last):
  File "C:\software\anoconda3\envs\nansat3.9\lib\site-packages\nansat\vrt.py", line 469, in __del__
    gdal.Unlink(self.filename)
  File "C:\software\anoconda3\envs\nansat3.9\lib\site-packages\osgeo\gdal.py", line 3360, in Unlink
    return _gdal.Unlink(*args)
RuntimeError: unknown error occurred

**Comment by GaotTian** [comment]
example :ASA_WSM_1PNDSI20120309_155143_000003363112_00270_52439_0000.N1

**Comment by jwLuo6413** [comment]
I think maybe you can test whether your "osgeo gdal" package is normal first. Try "from osgeo import gdal" to see if it can be imported properly.

**Comment by jwLuo6413** [comment]
@LooperzZ , your input "ASAR" filename is?
